# The plugin list for devkit

add_subdirectory(autoLoader)
add_subdirectory(exampleFalloff)
add_subdirectory(gameInputDevice)
add_subdirectory(geometrySurfaceConstraint)
add_subdirectory(iffInfoCmd)
add_subdirectory(iffPixelCmd)
add_subdirectory(iffPpmCmd)
add_subdirectory(ik2Bsolver)
add_subdirectory(lineManip)
add_subdirectory(lineManipContainer)
add_subdirectory(listRichSelectionCmd)
add_subdirectory(nameFilter)
add_subdirectory(pointManip)
add_subdirectory(polyRawExporter)
add_subdirectory(polyX3DExporter)
add_subdirectory(randomizerDevice)
add_subdirectory(richMoveCmd)
add_subdirectory(simpleEvaluationDraw)
add_subdirectory(simpleEvaluationNode)
add_subdirectory(splatDeformer)
add_subdirectory(sseDeformer)
add_subdirectory(stringFormatNode)
add_subdirectory(squareScaleManip)
add_subdirectory(squareScaleManipContext)
add_subdirectory(testNucleusNode)
add_subdirectory(testNsolverNode)
add_subdirectory(testNobjectNode)
add_subdirectory(testNpassiveNode)
add_subdirectory(threadTestCmd)
add_subdirectory(threadTestWithLocksCmd)
add_subdirectory(threadedBoundingBox)
add_subdirectory(threadingLockTests)
add_subdirectory(udpDevice)
add_subdirectory(MetadataSample)
add_subdirectory(MetadataXML)
add_subdirectory(XmlGeometryCacheDesc)

# The list from SuperConductor, used in standalone devkit
if (NOT INSIDE_MAYA)
	add_subdirectory(animImportExport)
	add_subdirectory(atomImportExport)
	add_subdirectory(glslShader)
    if (NOT APPLE)
        add_subdirectory(objExport)
    endif()
	add_subdirectory(testMTopologyEvaluator)
    if (FALSE)
        add_subdirectory(hlslShader)
    endif()
endif()

if(INSIDE_MAYA)
	if (NOT APPLE)
		# Requires GLEW
		add_subdirectory(cgFx)
	endif()
	if (WIN32)
		# Requires DirectX
		add_subdirectory(dx11Shader)
	endif()
endif()

# Qt Devkit examples
if (NOT INSIDE_MAYA)
	if(NOT EXISTS $ENV{DEVKIT_LOCATION}/Qt)
		message( WARNING "To build Qt examples you need to extract the Qt archive located in $ENV{DEVKIT_LOCATION}" ) 	
	else()
		add_subdirectory(grabUV)
		add_subdirectory(helixQtCmd )
		add_subdirectory(qtAdskStyleProxy )
		add_subdirectory(qtForms )
		add_subdirectory(saveSwatchesCmd)
		add_subdirectory(workspaceControlCmd)
	endif()
endif()

